import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/cart-context";
import { FavoriteListProvider } from "@/contexts/favorite-context";
import NavigationBar from "@/components/layout/navigation-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh flex flex-col font-[family-name:var(--font-geist-sans)]`}
      >
        <CartProvider>
          <FavoriteListProvider>
            <NavigationBar />
            {children}
          </FavoriteListProvider>
        </CartProvider>
      </body>
    </html>
  );
}
